version: 2.0

workspace: &workspace
  ~/objectstore

config_android: &config_android
  docker:
    - image: circleci/android:api-29
  working_directory: *workspace
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb

update_sdk: &update_sdk
  run:
    name: Update SDK
    command: |
      yes | sdkmanager --licenses || true
      sdkmanager "platform-tools" "platforms;android-29"

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: *workspace
    paths:
      - ./*/build

jobs:
  jobs:
    build_debug:
      <<: *config_android
      steps:
        - <<: *update_sdk
        - checkout
        - run:
            name: Download Dependencies
            command: ./gradlew dependencies
        - run:
            name: Assemble and Test APKs
            command: ./gradlew bundleDebug assembleDebug
        - store_artifacts:
            path: app/build/outputs
            destination: outputs
        - <<: *persist_workspace
  check:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
     - <<: *attach_workspace
      - run:
          name: Check app and dependencies
          command: ./gradlew app:lintDebug testDebug spotlessCheck
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_artifacts:
          path: ~/junit
